"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[character]
success_symbol = "[\\$](green bold)"
error_symbol = "[\\$](red bold)"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bg:#1e8449 fg:white bold"
format = "[ $path ]($style)"

[git_branch]
symbol = ''
format = '[](fg:#1e8449 bg:#c0392b)[ $symbol$branch ]($style)[](fg:#c0392b)'
style = "bg:#c0392b fg:white bold"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "red"
conflicted = '競合'
ahead = '先行'
behind = '遅延'
diverged = '分岐'
up_to_date = '最新'
untracked = '未追跡'
stashed = '退避'
modified = '変更'
staged = '準備'
renamed = '改名'
deleted = '削除'

# すべてのモジュールを有効化
